### ISSUE TITLE
NoClassDefFound javax/xml/bind/ValidationEvent...

### ISSUE THREAD

**Issue by gogro** [aerokube/selenoid-container-tests#10]
@4d5961e

starting tests via https://github.com/aerokube/images@e2fa90d 
./images firefox -b 78.4.0esr+build2-0ubuntu0.18.04.1 --channel esr -d 0.26.0 -t firefox:78.4.0esr --test

Results :                                                                                               
                                                    
Tests in error:                                                                                         
  TestScreenshot.testScreenshot » NoClassDefFound javax/xml/bind/ValidationEvent...
                                                    
Tests run: 22, Failures: 0, Errors: 1, Skipped: 1 

mvn --version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 14.0.1, vendor: Private Build, runtime: /usr/lib/jvm/java-14-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-1017-aws", arch: "amd64", family: "unix"

**Comment by vania-pooh** [comment]
@gogro we currently execute these tests with Java 8 as clearly stated here: https://github.com/aerokube/selenoid-container-tests/blob/master/pom.xml#L12 https://stackoverflow.com/questions/43574426/java-how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexceptio

**Comment by gogro** [comment]
my mistake, thanks Ivan
