### ISSUE TITLE
Chrome 92 GPU crashes

### ISSUE THREAD

**Issue by ruescar** [aerokube/selenoid-container-tests#12]
Most of the tests are timing out due to GPU crashes when launching Chrome 92

**Comment by ruescar** [comment]
Related issue: [chromium#1228625](https://bugs.chromium.org/p/chromium/issues/detail?id=1228625)

**Comment by vania-pooh** [comment]
@ruescar wouldn't it be easier to just wait for related issue to be fixed?

**Comment by ruescar** [comment]
@vania-pooh I agree with you. The only reason why I submitted the fix for this is because, we don't know yet when or if the issue will be fixed, and also because Chrome 92 has already been released to [Stable ](https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable) channel.
